package test.bett.auth.domain.exception;

public class UserNotFoundException extends RuntimeException {
}
